use anyhow::{Context, Result};
use regex::Regex;

use super::Plugin;

#[derive(Debug)]
pub struct Wordfence {
    name: String,
}

impl Plugin for Wordfence {
    fn check(
        &self,
        content: &str,
        _status: reqwest::StatusCode,
        _headers: &reqwest::header::HeaderMap,
    ) -> Result<bool> {
        if self.match_content(content)? {
            Ok(true)
        } else {
            Ok(false)
        }
    }

    fn name(&self) -> String {
        self.name.clone()
    }
}

impl Default for Wordfence {
    fn default() -> Self {
        Self::new()
    }
}

impl Wordfence {
    pub fn new() -> Self {
        Wordfence {
            name: "Wordfence (Defiant)".to_string(),
        }
    }

    pub fn match_content(&self, content: &str) -> Result<bool> {
        let patterns = [
            r"Generated by Wordfence",
            r"www\.wordfence\.com\/help\/\?query=locked-out",
            r"Advanced blocking in effect.",
        ];
        let combined_pattern = patterns.join("|");
        let pattern = Regex::new(&combined_pattern).context("Wordfence new regex error")?;
        Ok(pattern.is_match(content))
    }
}

#[cfg(test)]
mod tests {
    use std::fs;

    use crate::plugins::wordfence::Wordfence;

    fn get_html_content() -> String {
        fs::read_to_string("tests/html/wordfence.html").unwrap()
    }

    #[test]
    fn test_match_content() {
        let content = get_html_content();
        let waf = Wordfence::new();

        let res = waf.match_content(&content).unwrap();
        assert!(res)
    }
}
